### ISSUE TITLE
TPAC 2019 actions & resolutions

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/media-wg#5]
The idea is to check off items that have had an issue open (ideally listed next to it afterwards) or were done when no issue was actually needed.

**Actions**
- [X] mounir to add non-normative suggestions for behavior for pip window if remote/full screen engaged from main player w3c/picture-in-picture/issues/175
- [x] jer and mounir to talk to FOMS organizers about interest to co-host a Media WG F2F #12
- [X] jer to discuss moving media out of html w/ hober #11 
- [X] chcunningham to add examples to the Media Capabilities spec w3c/media-capabilities/issues/147
- [X] Joey_Parrish to add language to the privacy path WICG/hdcp-detection/issues/13
- [X] Joey_Parrish to look into reducing the number of HDCP versions we expose to collapse to those actually used WICG/hdcp-detection/issues/12
- [X] jer and mounir to create an issue on the media-wg repo about the resolution process, #2
- [X] jer and mounir to send CfC for publication as FPWD of Media Capabilities, PiP and Media Session the week after TPAC, #4
- [x] markw and GregFreedman to figure out who edits which spec (MSE/EME) among themselves
- [X]  mounir to swap his name with chcunningham as editor of Media Playback Quality #7
- [X] padenot to check whether someone from Mozilla can become editor of Media Session #6
- [X] scottlow to check for possible editors for MSE and EME #9
- [x] chcunningham to work with jer and propose an API that does some sort of eventing in a backward compatible way, and that converts the VideoPlaybackQuality object to a dictionary
- [X] mounir to talk to foolip to double check whether versioning is needed for MSE v2 WPT https://github.com/w3c/media-source/issues/242
- [X] tidoust to exchange with wolenetz on setting up MSE repo, updating boilerplate, ReSpec, etc. https://github.com/w3c/media-source/issues/241

**Resolutions**
- [x] Expose an API to expose key ID information from initialization data in order to find existing sessions w3c/encrypted-media/issues/467
- [X] The Media WG will have monthly calls, and encourage ad-hoc meetings on specific issues, #3 
- [X] Add Greg Whitworth as editor of Media Capabilities #8
- [x] Joey_Parrish to prepare a PR to integrate encryption scheme proposal in EME (W3C repo) (done, didn't track)
- [x] we can revert the framerate attribute back to a double (done, didn't track)
- [x] using a hint specific to low latency instead of content hint (done, didn't track)
- [X] Remove corruptedFrames from Media Playback Quality https://github.com/w3c/media-playback-quality/issues/5

/CC @tidoust @jernoble

**Comment by mounirlamouri** [comment]
All actions and resolutions have either be filed in a bug or done.
